name: Terraform CI/CD

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  
jobs:
  dev:
    uses: ComputerEnterprisesInc/zelis-tf-demo/.github/workflows/terraform-deploy-reusable.yml@main
    with:
      environment: dev
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  stage:
    uses: ComputerEnterprisesInc/zelis-tf-demo/.github/workflows/terraform-deploy-reusable.yml@main
    needs: dev
    with:
      environment: stage
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
  prod:
    uses: ComputerEnterprisesInc/zelis-tf-demo/.github/workflows/terraform-deploy-reusable.yml@main
    needs: stage
    with:
      environment: prod
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
